package com.rentflow.automation.model;

public enum AutomationActionType {
    CREATE_INTERNAL_TASK,
    CREATE_LEAD_FOLLOW_UP,
    SEND_QUOTE_REMINDER,
    SEND_CONTRACT_REMINDER,
    SEND_DEPOSIT_REMINDER,
    SEND_INVOICE_REMINDER,
    ASSIGN_DRIVER,
    ASSIGN_WAREHOUSE_OPERATOR,
    RETRY_WEBHOOK_DELIVERY,
    RETRY_INTEGRATION_EVENT,
    CREATE_MAINTENANCE_REVIEW_TASK,
    CREATE_DAMAGE_REVIEW_TASK
}
