package com.rentflow.ai.model;

public enum BookingAttentionSignal {
    INVENTORY_CONFLICT,
    WAREHOUSE_NOT_READY,
    PICKING_SHORTAGE,
    PACKING_INCOMPLETE,
    UNSIGNED_CONTRACT,
    UNPAID_DEPOSIT,
    OVERDUE_INVOICE,
    DELIVERY_UNASSIGNED,
    VEHICLE_UNASSIGNED,
    RETURN_OVERDUE,
    CUSTOMER_CHANGE_REQUEST,
    OPEN_DAMAGE_ISSUE
}
