package com.rentflow.notification.model;

public enum NotificationType {
    QUOTE_SENT,
    QUOTE_ACCEPTED,
    QUOTE_CHANGE_REQUESTED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    PAYMENT_RECEIVED,
    PAYMENT_DUE,
    PAYMENT_FAILED,
    INVOICE_CREATED,
    INVOICE_SENT,
    INVOICE_OVERDUE,
    DELIVERY_SCHEDULED,
    DELIVERY_ASSIGNED,
    DELIVERY_COMPLETED,
    CUSTOMER_REQUEST_CREATED,
    CUSTOMER_REQUEST_UPDATED,
    SYSTEM
}
