package com.rentflow.crm.model;

public enum ActivityType {
    NOTE,
    CALL,
    EMAIL,
    SMS,
    MEETING,
    STATUS_CHANGE,
    ASSIGNMENT,
    FOLLOW_UP_CREATED,
    FOLLOW_UP_COMPLETED,
    RENTAL_REQUEST_LINKED,
    CUSTOMER_LINKED,
    CUSTOMER_CREATED,
    QUOTE_CREATED,
    QUOTE_SENT,
    WON,
    LOST,
    REOPENED,
    AI_CONVERSATION_STARTED,
    AI_REQUIREMENTS_CAPTURED,
    AI_RENTAL_REQUEST_CREATED,
    AI_QUOTE_DRAFT_CREATED,
    AI_HUMAN_HANDOFF
}
