package com.rentflow.aisales.model;

public enum CopilotIntent {
    EXECUTIVE_SUMMARY,
    REVENUE_ANALYSIS,
    PROFITABILITY_ANALYSIS,
    SALES_ANALYSIS,
    LEAD_LOOKUP,
    QUOTE_LOOKUP,
    BOOKING_LOOKUP,
    CUSTOMER_LOOKUP,
    INVENTORY_ANALYSIS,
    AVAILABILITY_ANALYSIS,
    WAREHOUSE_ANALYSIS,
    DELIVERY_ANALYSIS,
    RETURN_ANALYSIS,
    DAMAGE_ANALYSIS,
    FINANCE_ANALYSIS,
    AR_ANALYSIS,
    INTEGRATION_HEALTH,
    DAILY_BRIEFING,
    ENTITY_EXPLANATION,
    ACTION_REQUEST,
    GENERAL_HELP,
    UNKNOWN
}
